# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Explog' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  ## Networking 
  pod 'Moya', '~> 11.0'
  pod 'Kingfisher', '~> 4.10.0'
 
  ## Container Viewcontroller 
  pod 'CaseContainer', '~> 0.9.0'

  ## KeyChain
  pod 'KeychainAccess', '~> 3.1.2'

  ## about chaining task in the asynchronous
  pod 'Bolts-Swift', '~> 1.4.0'

  ## UI
  pod 'SkyFloatingLabelTextField', '~> 3.6.0'
  pod 'ParallaxHeader', '~> 2.0.0'
  pod 'M13Checkbox'

  ## Abstract
  pod 'Then', '~> 2.4.0'
  pod 'SimpleCell', '~> 0.6.0'
  pod 'Square'

  ## generating Open-source information
  pod 'AcknowList', '~> 1.7.0'

  ## Firebase for Report
  pod 'Firebase/Core'
  pod 'Firebase/Database' 

  # Logging Service 
  pod 'SwiftyBeaver', '~> 1.6.1'

  # Pods for Explog
end

## ParallaxHeader didn't support to compile on Swift 4.2 in CLI
## just temporary action  
post_install do |installer|
  installer.pods_project.targets.each do |target|
      if ['ParallaxHeader', 'M13Checkbox'].include? target.name
          target.build_configurations.each do |config|
              config.build_settings['SWIFT_VERSION'] = '4.0'
          end
      end
  end
end

