force true
price_tier 0


app_review_information(
  first_name: "Ju",
  last_name: "Minjun",
  phone_number: "+82 010-8966-4111",
  email_address: "dev.mjun@gmail.com",
  demo_user: "traveler1@gmail.com",
  demo_password: "1234567890",
  notes: "To be needed Account when login in"
)

submission_information({    
    export_compliance_encryption_updated: false,
    export_compliance_uses_encryption: false,
    export_compliance_compliance_required: false, 
    content_rights_contains_third_party_content: false,
    add_id_info_uses_idfa: false
})

release_notes(
	{"ko-KR" => "국제화, 복원 및 보존 기능 추가"},
  {"en-US" => "Support for Internationalization, Preservation and Restoration"}
	)
automatic_release true

app_icon './fastlane/metadata/app_icon.jpg'

app_rating_config_path "./fastlane/metadata/itunes_rating_config.json"