# 1
price_tier 0

# 2
app_review_information(
  first_name: "Ju",
  last_name: "Minjun",
  phone_number: "+82 010-8966-4111",
  email_address: "dev.mjun@gmail.com",
  demo_user: "traveler@gmail.com",
  demo_password: "1234567890",
  notes: "To be needed Account when login in"
)

# 3
submission_information({    
    export_compliance_encryption_updated: true,
    export_compliance_uses_encryption: true,
    content_rights_contains_third_party_content: false,
    add_id_info_uses_idfa: false
})

# 4
automatic_release false

# 5
app_icon './Explog/Assets/Assets.xcassets/AppIcon.appiconset/ItunesArtwork@2x.png'

# 6
app_rating_config_path "./fastlane/metadata/itunes_rating_config.json"