# Uncomment the lines below you want to change by removing the # in the beginning
# A list of devices you want to take the screenshots from

devices([
  "iPhone X",
  "iPhone 8 Plus",
  "iPhone XS Max",
])

languages([
  "ko"
])

# The name of the scheme which contains the UI Tests
scheme("UITests")

# Where should the resulting screenshots be stored?
output_directory "./fastlane/screenshots"

# Clears previous screenshots
clear_previous_screenshots true

# Latest version of iOS
ios_version '11.0'

